"""add consent fields to business

Revision ID: 41331c43c70a
Revises: 1f423e2ce69e
Create Date: 2026-10-05 11:14:51.334808

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41331c43c70a"
down_revision: str | Sequence[str] | None = "1f423e2ce69e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesses",
        sa.Column(
            "editorial_consent",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "businesses",
        sa.Column(
            "image_consent",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "image_consent")
    op.drop_column("businesses", "editorial_consent")
    # ### end Alembic commands ###
