"""add suggestions claims and consent

Revision ID: 4e6bd8acae5a
Revises: 217cce117df7
Create Date: 2026-10-06 13:08:21.519277

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e6bd8acae5a"
down_revision: str | Sequence[str] | None = "217cce117df7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("county", sa.String(length=100), nullable=False),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("materials_raw", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("submitter_note", sa.Text(), nullable=True),
        sa.Column("submitter_email", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "business_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("claimant_name", sa.String(length=200), nullable=False),
        sa.Column("claimant_role", sa.String(length=50), nullable=False),
        sa.Column("claimant_contact", sa.String(length=200), nullable=False),
        sa.Column("correction_note", sa.Text(), nullable=True),
        sa.Column("editorial_consent", sa.Boolean(), nullable=False),
        sa.Column("image_consent", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("business_claims")
    op.drop_table("business_suggestions")
    # ### end Alembic commands ###
